version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'type: dependencies'
    commit-message:
      prefix: ci
    # Security updates only
    open-pull-requests-limit: 0
