name: CI

on:
  push:
    branches: [ci]

permissions: {}

env:
  API_DOMAIN: eternagame.org
  NODE_VERSION: 20.x
  BUILD_TYPE: prod

jobs:
  tmp:
    runs-on: macos-latest
    steps:
      - run: xcodebuild -help
