name: 'Upload Build'

on:
  workflow_dispatch:
    inputs:
      run-id:
        description: 'GitHub Actions run ID to use artifacts from'
        required: true
        type: number

permissions:
  actions: read

jobs:
  upload-ios:
    runs-on: macos-latest
  
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-ios
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ inputs.run-id }}
    
  upload-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-android
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ inputs.run-id }}
            